import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/review_model.dart';
import '../services/review_service.dart';
import 'auth_provider.dart';
import 'user_provider.dart';

/// Provider for the [ReviewService].
final reviewServiceProvider = Provider<ReviewService>((ref) {
  return ReviewService();
});

/// Streams all reviews for the global activity feed.
final allReviewsProvider = StreamProvider<List<ReviewModel>>((ref) {
  return ref.watch(reviewServiceProvider).watchAllReviews();
});

/// Streams reviews for a specific book.
final bookReviewsProvider = StreamProvider.family<List<ReviewModel>, String>((ref, bookId) {
  return ref.watch(reviewServiceProvider).watchReviewsForBook(bookId);
});

/// A notifier to manage review operations.
class ReviewNotifier extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  Future<void> postReview({
    required String bookId,
    required String bookTitle,
    String? bookThumbnail,
    required double rating,
    required String text,
  }) async {
    final user = ref.read(authProvider).value;
    final userProfile = ref.read(currentUserDataProvider).value;
    if (user == null || userProfile == null) return;

    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final review = ReviewModel(
        id: '', // Will be generated by Firestore
        userId: user.uid,
        userName: userProfile.displayName,
        userProfilePic: userProfile.profilePicUrl,
        bookId: bookId,
        bookTitle: bookTitle,
        bookThumbnail: bookThumbnail,
        rating: rating,
        reviewText: text,
        timestamp: DateTime.now(),
      );
      await ref.read(reviewServiceProvider).saveReview(review);
    });
  }

  Future<void> updateReview(ReviewModel review) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(reviewServiceProvider).saveReview(review);
    });
  }

  Future<void> deleteReview(String reviewId) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(reviewServiceProvider).deleteReview(reviewId);
    });
  }
}

final reviewActionProvider = AsyncNotifierProvider.autoDispose<ReviewNotifier, void>(
  ReviewNotifier.new,
);
