import 'package:freezed_annotation/freezed_annotation.dart';


// tell the Dart complier there are two other files part of this file 
part 'user_model.freezed.dart';
part 'user_model.g.dart';

/// [UserModel] is an immutable data class generated by the Freezed package.
///
/// **Why Freezed?**
/// 1. **Value Equality**: Unlike standard Dart classes, two [UserModel] objects are equal 
///    if their properties match (e.g., same `uid`, same `displayName`). This prevents 
///    unnecessary UI rebuilds in Riverpod when the data remains identical.
/// 
/// 2. **Deep Immutability**: All fields are final. Collections like `favoriteGenres` are 
///    automatically wrapped in an unmodifiable list to ensure data integrity.
/// 
/// 3. **Serialization**: The `fromJson` and `toJson` (generated in `.g.dart`) methods 
///    provide a seamless bridge between your Dart objects and Firestore's Map-based structure.
/// 
/// 4. **Safety**: It generates a `copyWith` method, allowing you to create a modified 
///    version of the user (e.g., updating a bio) while keeping other fields unchanged.
@freezed
abstract class UserModel with _$UserModel {
  const factory UserModel({
    required String uid,
    required String displayName,
    required String bio,
    required String profilePicUrl,
    required List<String> favoriteGenres,
    @Default([]) List<String> topFavoriteBookIds,
    @Default(0) int followerCount,
    @Default(0) int followingCount,
  }) = _UserModel;

  /// Connects to the generated `_$UserModelFromJson` in `user_model.g.dart`.
  factory UserModel.fromJson(Map<String, dynamic> json) => _$UserModelFromJson(json);
}
