// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbS0Loxb-Nx4266C0j9pSd0BSp4VxUC9s',
    appId: '1:553345211212:web:3d68f82c72ce38b5040de9',
    messagingSenderId: '553345211212',
    projectId: 'mysyeapp',
    authDomain: 'mysyeapp.firebaseapp.com',
    storageBucket: 'mysyeapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXITXB_fchfa4pF8WQ9fTvvWocoTY3vgA',
    appId: '1:553345211212:android:0bbb33d80cfa8c13040de9',
    messagingSenderId: '553345211212',
    projectId: 'mysyeapp',
    storageBucket: 'mysyeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6k4JD95WHhu0coXkCd5eqqb7VdL5OLQM',
    appId: '1:553345211212:ios:3f4e95a082953006040de9',
    messagingSenderId: '553345211212',
    projectId: 'mysyeapp',
    storageBucket: 'mysyeapp.firebasestorage.app',
    iosBundleId: 'com.example.syeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6k4JD95WHhu0coXkCd5eqqb7VdL5OLQM',
    appId: '1:553345211212:ios:3f4e95a082953006040de9',
    messagingSenderId: '553345211212',
    projectId: 'mysyeapp',
    storageBucket: 'mysyeapp.firebasestorage.app',
    iosBundleId: 'com.example.syeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbS0Loxb-Nx4266C0j9pSd0BSp4VxUC9s',
    appId: '1:553345211212:web:907d67caea941222040de9',
    messagingSenderId: '553345211212',
    projectId: 'mysyeapp',
    authDomain: 'mysyeapp.firebaseapp.com',
    storageBucket: 'mysyeapp.firebasestorage.app',
  );
}
